void* activarRobot(void* args);
void crearSecciones();
void esperarYRecibirProductos(int totalProductos, int* pesoRobot, void* aux);
void getLista(int* lista);
int getProductosAComprar(size_t seccionIndx, int pesoRobot, int productosDeseados);
int getRandomNumber(int min, int max);
void iniciarSeccion(void* aux);
void liberarSeccionAnterior(size_t seccionALiberar, int pesoRobot);
void printProductosAComprar(int id, int* lista);
void printLista(int* lista);
