void cleanSemaforos();
int faltanClientesPorAtender();
useconds_t getRandomTimePeriod(useconds_t min, useconds_t max);
void iniciarCajeros(pthread_t* cajero_threads);
void iniciarSemaforos();
void logOperacion(void* cajero, void* cliente);
void mandarClientesAlBanco(pthread_t* clientes);
void* realizarOperacionEmpresarial(void* args);
void* realizarOperacionGeneral(void* args);
void* serUnCajero(void* args);
